import type { CitationGraph } from '../types/citation'

export const MOCK_CITATION_GRAPH: CitationGraph = {
  nodes: [
    // Central case - the one we're viewing
    {
      id: 'puttaswamy',
      citation: 'AIR 2017 SC 4161',
      title: 'K.S. Puttaswamy v. Union of India',
      year: 2017,
      court: 'Supreme Court',
      importance: 5,
      type: 'central',
    },
    // Cases cited by Puttaswamy
    {
      id: 'kharak-singh',
      citation: 'AIR 1963 SC 1295',
      title: 'Kharak Singh v. State of UP',
      year: 1963,
      court: 'Supreme Court',
      importance: 4,
      type: 'cited',
    },
    {
      id: 'mp-sharma',
      citation: 'AIR 1954 SC 300',
      title: 'M.P. Sharma v. Satish Chandra',
      year: 1954,
      court: 'Supreme Court',
      importance: 3,
      type: 'cited',
    },
    {
      id: 'maneka-gandhi',
      citation: 'AIR 1978 SC 597',
      title: 'Maneka Gandhi v. Union of India',
      year: 1978,
      court: 'Supreme Court',
      importance: 5,
      type: 'cited',
    },
    {
      id: 'gobind',
      citation: 'AIR 1975 SC 1378',
      title: 'Gobind v. State of M.P.',
      year: 1975,
      court: 'Supreme Court',
      importance: 4,
      type: 'cited',
    },
    {
      id: 'francis-coralie',
      citation: 'AIR 1981 SC 746',
      title: 'Francis Coralie v. Union Territory of Delhi',
      year: 1981,
      court: 'Supreme Court',
      importance: 3,
      type: 'cited',
    },
    // Cases citing Puttaswamy
    {
      id: 'aadhaar',
      citation: 'AIR 2019 SC 4625',
      title: 'Aadhaar Constitutional Validity',
      year: 2019,
      court: 'Supreme Court',
      importance: 5,
      type: 'citing',
    },
    {
      id: 'whatsapp',
      citation: '2021 SCC OnLine Del 4149',
      title: 'WhatsApp v. Union of India',
      year: 2021,
      court: 'Delhi High Court',
      importance: 4,
      type: 'citing',
    },
    {
      id: 'matrimony',
      citation: '(2022) 10 SCC 641',
      title: 'X v. Y (Matrimonial Privacy)',
      year: 2022,
      court: 'Supreme Court',
      importance: 3,
      type: 'citing',
    },
    {
      id: 'surveillance',
      citation: '2023 SCC OnLine SC 682',
      title: 'PUCL v. Union of India (Surveillance)',
      year: 2023,
      court: 'Supreme Court',
      importance: 4,
      type: 'citing',
    },
    {
      id: 'data-protection',
      citation: '2024 SCC OnLine SC 156',
      title: 'Data Protection Authority Case',
      year: 2024,
      court: 'Supreme Court',
      importance: 4,
      type: 'citing',
    },
    // Secondary citations (cases cited by cited cases)
    {
      id: 'art-21-expansion',
      citation: 'AIR 1976 SC 1207',
      title: 'Article 21 Expansion Cases',
      year: 1976,
      court: 'Supreme Court',
      importance: 2,
      type: 'cited',
    },
  ],
  links: [
    // Puttaswamy cites these (refers to)
    {
      source: 'puttaswamy',
      target: 'kharak-singh',
      type: 'overruled',
      strength: 3,
    },
    {
      source: 'puttaswamy',
      target: 'mp-sharma',
      type: 'overruled',
      strength: 3,
    },
    {
      source: 'puttaswamy',
      target: 'maneka-gandhi',
      type: 'followed',
      strength: 3,
    },
    {
      source: 'puttaswamy',
      target: 'gobind',
      type: 'followed',
      strength: 2,
    },
    {
      source: 'puttaswamy',
      target: 'francis-coralie',
      type: 'refers_to',
      strength: 2,
    },
    // These cases cite Puttaswamy (cited by)
    {
      source: 'aadhaar',
      target: 'puttaswamy',
      type: 'followed',
      strength: 3,
    },
    {
      source: 'whatsapp',
      target: 'puttaswamy',
      type: 'followed',
      strength: 3,
    },
    {
      source: 'matrimony',
      target: 'puttaswamy',
      type: 'followed',
      strength: 2,
    },
    {
      source: 'surveillance',
      target: 'puttaswamy',
      type: 'followed',
      strength: 3,
    },
    {
      source: 'data-protection',
      target: 'puttaswamy',
      type: 'followed',
      strength: 3,
    },
    // Secondary connections
    {
      source: 'maneka-gandhi',
      target: 'art-21-expansion',
      type: 'refers_to',
      strength: 1,
    },
    {
      source: 'gobind',
      target: 'kharak-singh',
      type: 'distinguished',
      strength: 2,
    },
  ],
}
