AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Fargate deployment for scriptcentral-prod with ALB (HTTPS via ACM), PostgreSQL RDS (private subnet), and secure networking

Parameters:
  DBUsername:
    Type: String
    Default: masteruser
    Description: The database admin username

  DBPassword:
    Type: String
    NoEcho: true
    Default: AnZwIX5Zm8u7g2P
    Description: The database admin password

  DBName:
    Type: String
    Default: scriptcentral
    Description: The name of the PostgreSQL database

  ECRImage:
    Type: String
    Default: 274436154583.dkr.ecr.us-east-2.amazonaws.com/asmac/scriptcentral:latest
    Description: ECR image URI (e.g. 123456789.dkr.ecr.us-east-1.amazonaws.com/scriptcentral-prod:latest)

  ContainerPort:
    Type: Number
    Default: 3001
    Description: Port your app listens on inside the container

  CertificateArn:
    Type: String
    Default: arn:aws:acm:us-east-2:274436154583:certificate/2095c66b-b777-43e7-93d2-f019009cd9a7
    Description: ACM certificate ARN for the ALB (must be in the same region as the ALB)

  DomainName:
    Type: String
    Default: scriptcentral.ai
    Description: The domain name for Route53

  HostedZoneId:
    Type: String
    Default: Z03617912FYWAS24HZF0R
    Description: Route53 Hosted Zone ID

Resources:

  # --- VPC and Networking ---
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  DefaultRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [0, !GetAZs '']

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [1, !GetAZs '']

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.3.0/24
      MapPublicIpOnLaunch: false
      AvailabilityZone: !Select [0, !GetAZs '']

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.4.0/24
      MapPublicIpOnLaunch: false
      AvailabilityZone: !Select [1, !GetAZs '']

  SubnetRouteTableAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref RouteTable

  SubnetRouteTableAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref RouteTable

  # --- ECS Cluster ---
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: scriptcentral-prod-cluster

  # --- CloudWatch Logs ---
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/scriptcentral-prod
      RetentionInDays: 7

  # --- IAM Execution Role ---
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  # --- Task Definition ---
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: scriptcentral-task
      Cpu: '256'
      Memory: '512'
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      ExecutionRoleArn: !Ref TaskExecutionRole
      ContainerDefinitions:
        - Name: scriptcentral-container
          Image: !Ref ECRImage
          PortMappings:
            - ContainerPort: !Ref ContainerPort
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/scriptcentral-prod
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs

  # --- Security Groups ---
  # ALB: open 80/443 to the world
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP/HTTPS access to ALB
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

  # ECS tasks: only ALB can reach the container port
  ServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ALB to access ECS tasks
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref ContainerPort
          ToPort: !Ref ContainerPort
          SourceSecurityGroupId: !Ref ALBSecurityGroup

  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ECS access to RDS
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref ServiceSecurityGroup

  # --- Application Load Balancer ---
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: scriptcentral-alb
      Scheme: internet-facing
      Subnets:
        - !Ref PublicSubnet
        - !Ref PublicSubnet2
      SecurityGroups:
        - !Ref ALBSecurityGroup

  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: scriptcentral-alb-tg
      Port: !Ref ContainerPort
      Protocol: HTTP
      VpcId: !Ref VPC
      TargetType: ip
      HealthCheckProtocol: HTTP
      HealthCheckPath: /
      HealthCheckPort: traffic-port
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 5
      HealthCheckIntervalSeconds: 30

  # Listener : HTTP (80) -> redirect to HTTPS (443)
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Protocol: HTTP
      Port: 80
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: '443'
            StatusCode: HTTP_301

  # Listener : HTTPS (443) with ACM cert -> forward to target group
  HTTPSListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Protocol: HTTPS
      Port: 443
      Certificates:
        - CertificateArn: !Ref CertificateArn
      # Optionally set a stricter SSL policy. If unsure, leave default or set one you prefer.
      # SslPolicy: ELBSecurityPolicy-2016-08
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup

  # --- Route53 Records ---
  DNSRecordApex:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt ApplicationLoadBalancer.DNSName
        HostedZoneId: !GetAtt ApplicationLoadBalancer.CanonicalHostedZoneID
        EvaluateTargetHealth: false

  DNSRecordWWW:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub "www.${DomainName}"
      Type: CNAME
      TTL: 300
      ResourceRecords:
        - !Ref DomainName

  DNSMX:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: MX
      TTL: 14400
      ResourceRecords:
        - "5 mx1.hostinger.com."
        - "10 mx2.hostinger.com."

  DNSTXTSPF:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: TXT
      TTL: 3600
      ResourceRecords:
        - "\"v=spf1 include:_spf.mail.hostinger.com ~all\""

  DNSTXTDmarc:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub "_dmarc.${DomainName}"
      Type: TXT
      TTL: 3600
      ResourceRecords:
        - "\"v=DMARC1; p=none\""

  DNSDKIMa:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub "hostingermail-a._domainkey.${DomainName}"
      Type: CNAME
      TTL: 300
      ResourceRecords:
        - "hostingermail-a.dkim.mail.hostinger.com."

  DNSDKIMb:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub "hostingermail-b._domainkey.${DomainName}"
      Type: CNAME
      TTL: 300
      ResourceRecords:
        - "hostingermail-b.dkim.mail.hostinger.com."

  DNSDKIMc:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub "hostingermail-c._domainkey.${DomainName}"
      Type: CNAME
      TTL: 300
      ResourceRecords:
        - "hostingermail-c.dkim.mail.hostinger.com."

  # --- ECS Service ---
  ECSService:
    Type: AWS::ECS::Service
    DependsOn: HTTPSListener
    Properties:
      Cluster: !Ref ECSCluster
      LaunchType: FARGATE
      DesiredCount: 1
      TaskDefinition: !Ref TaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref PublicSubnet
            - !Ref PublicSubnet2
          SecurityGroups:
            - !Ref ServiceSecurityGroup
      LoadBalancers:
        - TargetGroupArn: !Ref ALBTargetGroup
          ContainerName: scriptcentral-container
          ContainerPort: !Ref ContainerPort

  # --- S3 Bucket ---
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: scriptcentral-ai-pdx-prod
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  # --- RDS Subnet Group ---
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS instance
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2

  # --- RDS PostgreSQL ---
  ScriptCentralDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: scriptcentral-db
      AllocatedStorage: 20
      EnableIAMDatabaseAuthentication: true
      DBInstanceClass: db.t4g.micro
      Engine: postgres
      EngineVersion: 17.4
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBName: !Ref DBName
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      PubliclyAccessible: false
      BackupRetentionPeriod: 7
      MultiAZ: false
      StorageType: gp2

Outputs:
  AppURL:
    Description: ALB DNS name to access the app (HTTPS)
    Value: !Sub "https://${ApplicationLoadBalancer.DNSName}"

  ALBDNSName:
    Description: Raw ALB DNS name
    Value: !GetAtt ApplicationLoadBalancer.DNSName
